version: '3.9'

services:
  web:
    build: ./backend
    container_name: flask_app
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db:5432/itam_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: sh -c "alembic upgrade head && python app.py"
  
  db:
    image: postgres:17.2
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=itam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d itam_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: